<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Locations;

class MedanLocationsSeeder extends Seeder
{
    public function run()
    {
        $locations = [
            ['name' => 'Terminal Amplas', 'state' => 'Sumatera Utara', 'place' => 'Medan Amplas', 'address' => 'Jl. Sisingamangaraja No. 12'],
            ['name' => 'Terminal Pinang Baris', 'state' => 'Sumatera Utara', 'place' => 'Medan Sunggal', 'address' => 'Jl. Gatot Subroto KM 5.5'],
            ['name' => 'Medan Mall', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. MT Haryono'],
            ['name' => 'Sun Plaza', 'state' => 'Sumatera Utara', 'place' => 'Medan Polonia', 'address' => 'Jl. KH Zainul Arifin No. 7'],
            ['name' => 'Cambridge City Square', 'state' => 'Sumatera Utara', 'place' => 'Medan Selayang', 'address' => 'Jl. S. Parman'],
            ['name' => 'Medan Fair Plaza', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Gatot Subroto'],
            ['name' => 'Focal Point', 'state' => 'Sumatera Utara', 'place' => 'Medan Selayang', 'address' => 'Jl. Gagak Hitam'],
            ['name' => 'Plaza Medan Fair', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Gatot Subroto'],
            ['name' => 'Centre Point Mall', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jawa'],
            ['name' => 'Medan Central', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Putri Hijau'],
            ['name' => 'Stasiun Kereta Api Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Stasiun KA'],
            ['name' => 'Bandara Kualanamu', 'state' => 'Sumatera Utara', 'place' => 'Deli Serdang', 'address' => 'Jl. Bandara Kualanamu'],
            ['name' => 'Thamrin Plaza', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. M.H Thamrin'],
            ['name' => 'Palladium Mall', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Kapten Maulana Lubis'],
            ['name' => 'Ring Road City Walks', 'state' => 'Sumatera Utara', 'place' => 'Medan Selayang', 'address' => 'Jl. Ring Road'],
            ['name' => 'Manhattan Times Square', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Gatot Subroto'],
            ['name' => 'Medan Zoo', 'state' => 'Sumatera Utara', 'place' => 'Medan Tuntungan', 'address' => 'Jl. Simalingkar'],
            ['name' => 'Istana Maimun', 'state' => 'Sumatera Utara', 'place' => 'Medan Maimun', 'address' => 'Jl. Brigjen Katamso'],
            ['name' => 'Masjid Raya Al Mashun', 'state' => 'Sumatera Utara', 'place' => 'Medan Maimun', 'address' => 'Jl. Sisingamangaraja'],
            ['name' => 'Lapangan Merdeka', 'state' => 'Sumatera Utara', 'place' => 'Medan Baru', 'address' => 'Jl. Balai Kota'],
            // ... tambahkan 80 lokasi lainnya
            ['name' => 'Universitas Sumatera Utara', 'state' => 'Sumatera Utara', 'place' => 'Medan Baru', 'address' => 'Jl. Dr. Mansyur'],
            ['name' => 'UNIMED', 'state' => 'Sumatera Utara', 'place' => 'Medan Helvetia', 'address' => 'Jl. Willem Iskandar'],
            ['name' => 'UISU', 'state' => 'Sumatera Utara', 'place' => 'Medan Area', 'address' => 'Jl. Sisingamangaraja'],
            ['name' => 'UMSU', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Kapten Muchtar Basri'],
            ['name' => 'RS Adam Malik', 'state' => 'Sumatera Utara', 'place' => 'Medan Tuntungan', 'address' => 'Jl. Bunga Lau'],
            ['name' => 'RS Columbia Asia', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Listrik'],
            ['name' => 'RS Royal Prima', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Ayahanda'],
            ['name' => 'RS Murni Teguh', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jawa'],
            ['name' => 'Pasar Petisah', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Petisah'],
            ['name' => 'Pasar Sambas', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Sambas'],
            ['name' => 'Pasar Simpang Limun', 'state' => 'Sumatera Utara', 'place' => 'Medan Amplas', 'address' => 'Jl. Simpang Limun'],
            ['name' => 'Pasar Sukaramai', 'state' => 'Sumatera Utara', 'place' => 'Medan Area', 'address' => 'Jl. AR Hakim'],
            ['name' => 'Pasar Aksara', 'state' => 'Sumatera Utara', 'place' => 'Medan Timur', 'address' => 'Jl. Aksara'],
            ['name' => 'Pasar Sei Sikambing', 'state' => 'Sumatera Utara', 'place' => 'Medan Helvetia', 'address' => 'Jl. Gatot Subroto'],
            ['name' => 'Pasar Medan Mall', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. MT Haryono'],
            ['name' => 'Pasar Merah', 'state' => 'Sumatera Utara', 'place' => 'Medan Area', 'address' => 'Jl. Pasar Merah'],
            ['name' => 'Pasar Pagi', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Asia'],
            ['name' => 'Pasar Halat', 'state' => 'Sumatera Utara', 'place' => 'Medan Area', 'address' => 'Jl. Halat'],
            ['name' => 'Pasar Bakti', 'state' => 'Sumatera Utara', 'place' => 'Medan Maimun', 'address' => 'Jl. Bakti'],
            ['name' => 'Pasar Brayan', 'state' => 'Sumatera Utara', 'place' => 'Medan Barat', 'address' => 'Jl. KL Yos Sudarso'],
            ['name' => 'Hotel JW Marriott', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Putri Hijau No. 10'],
            ['name' => 'Hotel Grand Aston', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Balai Kota No. 1'],
            ['name' => 'Hotel Santika', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Kapten Maulana Lubis No. 7'],
            ['name' => 'Hotel Grand Mercure', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Sutomo No. 1'],
            ['name' => 'Hotel Aryaduta', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Kapten Maulana Lubis No. 8'],
            ['name' => 'Hotel Swiss-Belinn', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. S. Parman No. 217'],
            ['name' => 'Hotel Grand Inna', 'state' => 'Sumatera Utara', 'place' => 'Medan Baru', 'address' => 'Jl. Balai Kota No. 2'],
            ['name' => 'Hotel Grand Delta', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Gatot Subroto No. 138'],
            ['name' => 'Hotel Madani', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Sisingamangaraja No. 1'],
            ['name' => 'Hotel Garuda Plaza', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Sisingamangaraja No. 18'],
            ['name' => 'Kantor Gubernur Sumut', 'state' => 'Sumatera Utara', 'place' => 'Medan Maimun', 'address' => 'Jl. Pangeran Diponegoro No. 30'],
            ['name' => 'Kantor Walikota Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Baru', 'address' => 'Jl. Kapten Maulana Lubis No. 2'],
            ['name' => 'Kantor DPRD Sumut', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Imam Bonjol No. 5'],
            ['name' => 'Kantor DPRD Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Kapten Maulana Lubis No. 1'],
            ['name' => 'Kantor Pos Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Pos No. 1'],
            ['name' => 'Kantor PLN Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. K.H. Wahid Hasyim No. 10'],
            ['name' => 'Kantor Telkom Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Prof. HM. Yamin SH No. 2'],
            ['name' => 'Kantor BRI Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Putri Hijau No. 4'],
            ['name' => 'Kantor BNI Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Pemuda No. 12'],
            ['name' => 'Kantor Mandiri Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Balai Kota No. 8'],
            ['name' => 'Kantor BCA Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Diponegoro No. 28'],
            ['name' => 'Kantor BTN Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Pemuda No. 10-A'],
            ['name' => 'Kantor BPJS Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. K.H. Wahid Hasyim No. 1'],
            ['name' => 'Kantor Pajak Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Kota', 'address' => 'Jl. Suka Mulia No. 17-A'],
            ['name' => 'Kantor Imigrasi Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Timur', 'address' => 'Jl. Gatot Subroto KM 6.2'],
            ['name' => 'Kantor BPN Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Putri Hijau No. 6'],
            ['name' => 'Kantor Samsat Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Putri Hijau No. 14'],
            ['name' => 'Kantor Disdukcapil Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Iskandar Muda No. 270'],
            ['name' => 'Kantor Dinas Pendidikan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Pelita IV No. 77'],
            ['name' => 'Kantor Dinas Kesehatan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Williem Iskandar Pasar V'],
            ['name' => 'Kantor Dinas Perhubungan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Pinang Baris No. 114'],
            ['name' => 'Kantor Dinas PU Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution No. 6'],
            ['name' => 'Kantor Dinas Kebersihan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Pinang Baris No. 114'],
            ['name' => 'Kantor Dinas Pariwisata Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pertanian Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perindustrian Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perdagangan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Koperasi Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Tenaga Kerja Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Sosial Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pemuda dan Olahraga Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Kebudayaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Lingkungan Hidup Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perumahan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pemadam Kebakaran Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perpustakaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Kearsipan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Komunikasi Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Informatika Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Statistik Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perencanaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Keuangan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pendapatan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pertanahan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perikanan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Peternakan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Kehutanan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perkebunan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pertambangan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Energi Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Penanaman Modal Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perizinan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Ketenagakerjaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Transmigrasi Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pemberdayaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Perlindungan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pengendalian Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pembinaan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pengawasan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Penelitian Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution'],
            ['name' => 'Kantor Dinas Pengembangan Medan', 'state' => 'Sumatera Utara', 'place' => 'Medan Petisah', 'address' => 'Jl. Jend. Besar A.H. Nasution']
        ];

        foreach ($locations as $location) {
            $location['created_by_id'] = 1; // Assuming admin user has ID 1
            $location['updated_by_id'] = 1;
            Locations::create($location);
        }
    }
} 